# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Marginal Byte
email: erichfeng@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Better, one byte at a time.
twitter_username: ehfeng
github_username: ehfeng
exclude:
- Gemfile
- Gemfile.lock

sass:
  sass_dir: _sass

# Build settings
markdown: kramdown